name: create-design-tokens
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Install dependencies
      - run: npm install
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer tokens/raw.json tokens/transformed/global.json global
      # Create a hs theme, exclude the global tokens
      - run: npx token-transformer tokens/raw.json tokens/transformed/brand-one.json brand-one global
      # run Style Dictionary translate script to create platform deliverables
      - run: node dictionary.js
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updates design tokens